interface ZIF_UITB_C_CTM_STYLE
  public .


  constants DEFAULT type I value CL_TREE_MODEL=>STYLE_DEFAULT ##NO_TEXT.
  constants INVERTED_BLUE type I value CL_TREE_MODEL=>STYLE_INTENSIFIED ##NO_TEXT.
  constants INVERTED_GRAY type I value CL_TREE_MODEL=>STYLE_INACTIVE ##NO_TEXT.
  constants INVERTED_LIGHT_RED type I value CL_TREE_MODEL=>STYLE_INTENSIFD_CRITICAL ##NO_TEXT.
  constants LIGHT_BLUE type I value CL_TREE_MODEL=>STYLE_EMPHASIZED_A ##NO_TEXT.
  constants LIGHT_GRAY_BLUE type I value CL_TREE_MODEL=>STYLE_EMPHASIZED_B ##NO_TEXT.
  constants LIGHT_GREEN type I value CL_TREE_MODEL=>STYLE_EMPHASIZED_POSITIVE ##NO_TEXT.
  constants LIGHT_ORANGE type I value CL_TREE_MODEL=>STYLE_EMPHASIZED_C ##NO_TEXT.
  constants LIGHT_RED type I value CL_TREE_MODEL=>STYLE_EMPHASIZED_NEGATIVE ##NO_TEXT.
  constants LIGHT_YELLOW type I value CL_TREE_MODEL=>STYLE_EMPHASIZED ##NO_TEXT.
endinterface.
